# Generated by Django 5.2.11 on 2026-02-08 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveBigIntegerField()),
                ('snapshot_bytes', models.BinaryField()),
                ('kind', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('restore', 'Restore')], max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc_snapshots', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='documents.document')),
            ],
            options={
                'ordering': ('-seq',),
                'indexes': [models.Index(fields=['document', 'seq'], name='doc_snapshot_seq_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveBigIntegerField()),
                ('update_bytes', models.BinaryField()),
                ('size_bytes', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc_updates', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='documents.document')),
            ],
            options={
                'ordering': ('seq',),
                'indexes': [models.Index(fields=['document', 'seq'], name='doc_update_seq_idx')],
                'unique_together': {('document', 'seq')},
            },
        ),
    ]
